env:
  node: true

extends:
  - eslint:recommended

root: true

rules:
  eol-last: error
  eqeqeq: error
  handle-callback-err: error
  indent: [error, 2]
  no-unused-vars: [error, {vars: all, args: none}]
  one-var: [error, never]
  quotes: [error, single]
  semi: [error, always]
